/**
 * 定义动作ID
 */
ActionId = {
    MAIN_CHARACTER_STAND : 100,
    MAIN_CHARACTER_WALK : 110,
    MAIN_CHARACTER_RUN : 120,
    MAIN_CHARACTER_JUMP : 130,
    MAIN_CHARACTER_HIT : 140,
    MAIN_CHARACTER_HURT : 150
};